# Generated by Django 4.1.10 on 2023-08-24 14:56

from django.db import migrations, models
import djongo.storage


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_image_tags_remove_book_author_remove_book_genre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(storage=djongo.storage.GridFSStorage(collection='myfiles'), upload_to='images'),
        ),
    ]
