# Generated by Django 4.1.10 on 2023-08-26 12:28

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('catalog', '0006_rename_картинка_image_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tags',
        ),
        migrations.RemoveField(
            model_name ='image',
            name = 'tags'
        ),
        migrations.AddField(
            model_name='image',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
